package algonquin.cst2335.project;

import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.TextView;
import android.widget.Toast;

import androidx.appcompat.app.AppCompatActivity;

public class LoginPage extends AppCompatActivity {

    TextView txtView1, txtView2, txtView3, txtView4;
    EditText edtText1, edtText2, edtText3;
    Button button;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        txtView1=(TextView) findViewById(R.id.txtView1);
        txtView2=(TextView) findViewById(R.id.txtView2);
        txtView3=(TextView) findViewById(R.id.txtView3);
        txtView4=(TextView) findViewById(R.id.txtView4);
        edtText1=(EditText) findViewById(R.id.edtText1);
        edtText2=(EditText) findViewById(R.id.edtText2);
        edtText3=(EditText) findViewById(R.id.edtText3);
        button=(Button) findViewById(R.id.button);
        super.onCreate(savedInstanceState);
        setContentView(R.layout.login_page);

        button.setOnClickListener(new View.OnClickListener() {
            String name=edtText1.getText().toString();
            String email=edtText2.getText().toString();
            String password = edtText3.getText().toString();
            @Override
            public void onClick(View v) {
                if(name!=null && email!=null ){
                    return;
                }
                if (verifyPassword(password)) {
                    // Successful login, proceed to next page
                    Intent intent = new Intent(LoginPage.this, MainActivityTwo.class); // Replace NextActivity with your target activity
                    startActivity(intent);
                } else {
                    Toast.makeText(LoginPage.this, "Password must contain at least 6 characters, including uppercase, lowercase, number, and special character", Toast.LENGTH_SHORT).show();
                }
            }
        });
    }

    public boolean verifyPassword(String password) {
        // Length will detect the length of the password entered by the user
        int length=password.length();

        // Created  upper case, lower case, is a number or has special character as false
        // so that we can detect the conditions later
        boolean isUpperCase, isLowerCase, isNumber, isSpecialChar;
        isUpperCase=false;
        isLowerCase=false;
        isNumber=false;
        isSpecialChar=false;

        /* This is the most important step in this code
         * Here, we are firstly converting the password entered by user
         * to Character array which means each word is separated
         * for checking everything according to the condition
         */
        for(char c: password.toCharArray()){
            /* First condition to check is whether at least any one character is upper case or not
             * if condition  is upper case then it returns true
             */
            if(Character.isUpperCase(c)){
                isUpperCase=true;
            }
            /*
             * Here, condition if any charater is lower case is checked
             */
            if(Character.isLowerCase(c)){
                isLowerCase=true;
            }
            /*
             * Now third condition is checked
             * if any character is digit
             */
            if(Character.isDigit(c)){
                isNumber=true;
            }
            /*
             * The last condition if the character is not
             * a letter or a digit which means it is a special character
             */
            if(!Character.isLetterOrDigit(c)){
                isSpecialChar=true;
            }
        }

        /*
         * Lastly when all the conditions are checked and are true only
         * then password is successfully login otherwise it will show the message to
         * add special character, upper, lower case and a digit.
         */
        return length>=6 && isUpperCase && isLowerCase && isNumber && isSpecialChar;
    }
}
